### ISSUE TITLE
Recrutement automatisé par MP

### ISSUE THREAD

**Issue by iv-stpn** [EFREI-Horizon/MonkaBot#19]
Les personnes intéressés par rejoindre l'association peuvent réagir à un message particulier sur le serveur leur permettant de commencer une démarche automatisé avec un le bot par MP

Le bot envoie une série de message décrivant l'association, demandant à la personne quel pôle il/elle serait intéressé(e) par rejoindre, puis demande des détails pour soumettre une candidature

TODO: messages dans le détails, suite des informations à donner pour la candidature

**Comment by iv-stpn** [comment]
Oups j'avais oublié que je l'avais déjà faite cette issue...
C'est possible de la merge avec l'autre ?

**Comment by noftaly** [comment]
Tu ne peux pas merge, mais tu peux la close :D
